stock_market_analytics:  # Must match the 'profile:' name in your dbt_project.yml
  target: dev
  outputs:
    dev:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
      role: "{{ env_var('SNOWFLAKE_ROLE', 'DATA_PIPELINE_ROLE') }}"  
      database: "{{ env_var('SNOWFLAKE_DATABASE', 'STOCKS') }}"
      warehouse: "{{ env_var('SNOWFLAKE_WAREHOUSE', 'COMPUTE_WH') }}"
      schema: "{{ env_var('SNOWFLAKE_SCHEMA', 'COMMON') }}"
      threads: 4
      client_session_keep_alive: true  # Recommended for long runs